name: Full Stack Deployment using OIDC + SSM

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ################################################
      # Configure AWS using OIDC (no keys needed)
      ################################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::542622959484:role/cicd-rama
          aws-region: us-east-1

      ################################################
      # Deploy via SSM
      ################################################
      - name: Deploy Application via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0414a66008461dbc5 \
            --document-name "AWS-RunShellScript" \
            --comment "Full Stack Deployment" \
            --parameters 'commands=[

              "set -e",

              "cd /home/ec2-user",

              "echo ---------- SOURCE CODE UPDATE ----------",

              "if [ ! -d Java-springboot-project ]; then \
                  git clone https://github.com/CloudTechDevOps/Java-springboot-project.git; \
               else \
                  cd Java-springboot-project && git reset --hard && git pull origin main && cd ..; \
               fi",

              "cd Java-springboot-project",

              "echo ---------- FRONTEND DEPLOYMENT ----------",

              "cd frontend",

              "if [ ! -d venv ]; then python3 -m venv venv; fi",

              "venv/bin/python -m pip install --upgrade pip",

              "venv/bin/pip install -r requirements.txt",

              "pkill -f streamlit || true",

              "nohup venv/bin/python -m streamlit run app.py --server.address=0.0.0.0 --server.port=8501 > streamlit.log 2>&1 &",

              "echo ---------- BACKEND DEPLOYMENT ----------",

              "cd ../backend",

              "mvn clean package -DskipTests",

              "JAR=$(ls target/*.jar | head -n 1)",

              "pkill -f \"java -jar\" || true",

              "nohup java -jar $JAR > backend.log 2>&1 &"

            ]'
